<?php $this->layout('layout::default', ['title' => '404 Not Found']) ?>

<div class="space-y-4">
    <h1 class="text-red-500 text-4xl font-extrabold">Oops! This is awkward.</h1>
    <p>We encountered a <strong>404 Not Found error</strong>.</p>
    <p>
        You are looking for something that doesn't exist or may have moved. Check out one of the links on this page
        or head back to <a href="/" class="underline underline-offset-4 decoration-emerald-600">Home</a>.
    </p>
</div>
