<header class="mb-10 bg-emerald-600 text-white text-center p-4 drop-shadow-lg">
    <a class="text-4xl" href="<?= baseUrl() ?>"><?= setting('app.name') ?></a>
    <div class="md:hidden text-center my-5">
        <div x-data="{ open: false }">
            <button @click="open = ! open"
                    class="btn bg-white text-black border-b-4 border-emerald-700 active:border-0">
                Menu
            </button>

            <div x-show="open" @click.outside="open = false" class="p-2">
                <?php foreach (setting('menu.header') as $menu): ?>
                    <a href="<?= $menu['link'] ?>" class="mr-5 btn"><?= $menu['text'] ?></a>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <div class="hidden md:block text-center my-5">
        <div class="flex items-center">
            <?php foreach (setting('menu.header') as $menu): ?>
                <a href="<?= $menu['link'] ?>" class="mr-5 btn"><?= $menu['text'] ?></a>
            <?php endforeach; ?>
        </div>
    </div>
</header>