<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <title><?= $this->e($title) ?> - mezzio</title>
    <link rel="shortcut icon" href="https://getlaminas.org/images/favicon/favicon.ico"/>
    <link rel="stylesheet" href="/static/css/tailwind.min.css">
    <?= $this->section('stylesheets') ?>
</head>
<body>

<header class="mb-10 bg-emerald-600 text-white text-center">
    <span class="text-4xl"><?= setting('app.name') ?></span>
</header>

<div>
    <main class="container">
        <?= $this->section('content') ?>
    </main>
</div>

<footer class="border-t-4 border-t-emerald-600 bg-emerald-100 mt-10">
    <div>
        <?php if ($this->section('footer')): ?>
            <?= $this->section('footer') ?>
        <?php else: ?>
            <p>
                &copy; <?= date('Y') ?> <a href="<?= setting('app.url') ?>"><?= setting('app.name') ?></a>
            </p>
        <?php endif ?>
    </div>
</footer>

<script src="/static/js/alpine.min.js"></script>
<?= $this->section('javascript') ?>
</body>
</html>
