<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <title><?= $this->e($title) ?> - mezzio</title>
    <link rel="shortcut icon" href="https://getlaminas.org/images/favicon/favicon.ico"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter&family=JetBrains+Mono&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/tailwind.min.css">
    <?= $this->section('stylesheets') ?>
</head>
<body>

<?= $this->insert('partials::_header') ?>

<div class="w-full md:w-4/5 lg:w-2/3 mx-auto">
    <main class="container p-4">
        <?= $this->section('content') ?>
    </main>
</div>

<footer class="border-t-4 border-t-emerald-600 bg-emerald-100 mt-10 p-4">
    <div class="text-center">
        <?php if ($this->section('footer')): ?>
            <?= $this->section('footer') ?>
        <?php else: ?>
            <p>
                &copy; <?= date('Y') ?>
                <a class="underline underline-offset-4 decoration-emerald-600"
                   href="<?= setting('app.url') ?>" target="_blank">
                    <?= setting('app.name') ?>
                </a>
            </p>
        <?php endif ?>
    </div>
</footer>

<script src="/static/js/alpine.min.js"></script>
<?= $this->section('javascript') ?>
</body>
</html>
