baseurl: /SimplyFramework
highlighter: rouge
markdown: kramdown
permalink: date
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
title: SimplyDi Framework
description: A FullStack PHP Framework based on Mezzio Middleware Skeleton
remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap